pipeline {
    agent any

    triggers{
        githubPush()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'cd LMS_APP && pip install --break-system-packages -r requirements.txt'
            }
        }

        stage('Test') {
            steps {
                sh 'cd LMS_APP && PYTHONPATH=. pytest'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'cd LMS_APP && docker build -t hritika1/lms_app:latest .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-cred',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push hritika1/lms_app:latest
                    '''
                }
            }
        }
    }
    post{
        success{
            emailext(
                subject: "SUCCESS ${env.JOB_NAME}  #${env.BUILD_NUMBER}",
                body: """
                    <h2>Jenkins build Successful</h2>
                    <p>
                        <b>URL</b>: ${env.BUILD_URL}
                    </p>
                """,
                to: "44hritikagore@gmail.com"
            )
        }

        failure{
            emailext(
                subject: "FAILED ${env.JOB_NAME}  #${env.BUILD_NUMBER}",
                body: """
                    <h2>Jenkins build Failed</h2>
                    <p>
                        <b>URL</b>: ${env.BUILD_URL}
                    </p>
                """,
                to: "44hritikagore@gmail.com"
            )
        }
    }

}