pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {

        stage('Install Dependencies') {
            steps {
                sh 'cd LMS_APP && pip install --break-system-packages -r requirements.txt'
            }
        }

        stage('Test') {
            steps {
                sh '''
                    cd LMS_APP

                    export DB_USER=root
                    export DB_PASSWORD=test
                    export DB_HOST=localhost
                    export DB_PORT=3306
                    export DB_NAME=lms_db

                    export SECRET_KEY=test-secret-key
                    export JWT_SECRET_KEY=test-jwt-secret-key

                    PYTHONPATH=. pytest
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                stage('Test') {
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-cred',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push hritika1/lms_app:latest
                    '''
                }
            }
        }
    }

    post {
        success {
            emailext(
                subject: "SUCCESS ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
                    <h2>Jenkins build Successful!!</h2>
                    <p>
                        <b>URL:</b> ${env.BUILD_URL}
                    </p>
                """,
                to: "44hritikagore@gmail.com"
            )
        }

        failure {
            emailext(
                subject: "FAILED ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
                    <h2>Jenkins build Failed</h2>
                    <p>
                        <b>URL:</b> ${env.BUILD_URL}
                    </p>
                """,
                to: "44hritikagore@gmail.com"
            )
        }
    }
}