apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Lms@123"
  DB_PASSWORD: "Lms@123"
  MYSQL_USER: "root"
  MYSQL_DB_URL: "mysql+mysqlconnector://root:Lms@123@mysql-service:3306/lms_db"
  SECRET_KEY: "aec4c18e14b5cad59e28416466b971b22103ad096fec3f3535d2bbc57246e810"
  JWT_SECRET_KEY: "20915fae250ac13188859317455e8f7ba69dc0b81b4de6707b86f7f94cb02476"
